# src/utils.py
import numpy as np

class Minutia:
    def __init__(self, x, y, angle, type=None):
        self.x = int(x)
        self.y = int(y)
        self.angle = float(angle) # Ensure radians if possible, SDK usually returns radians or degrees (check SDK)
        self.type = type

def load_minutiae_from_file(filepath):
    """Parses the .txt file generated by your extract_features.py"""
    minutiae = []
    with open(filepath, 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 3:
                # Assuming format: x y angle
                m = Minutia(float(parts[0]), float(parts[1]), float(parts[2]))
                minutiae.append(m)
    return minutiae